version: 2
sources:
  - name: main
    tables:
      - name: observations
        description: "Weather observations from all stations"
      - name: stations
        description: "Weather station URLs from API"
        
models:
  - name: dim_stations
    description: "Unique weather stations with their locations extracted from observations data."
    
  - name: fact_observations
    description: "Cleaned fact table of weather observations with invalid data removed and calculated fields added."
    columns:
      - name: observation_id
        description: "Unique identifier for each observation"
      - name: station_id
        description: "Station identifier"
      - name: observation_timestamp
        description: "Timestamp of the observation"
      - name: temperature_degC
        description: "Temperature in Celsius (validated range: -100 to 60)"
        
  - name: fact_daily_weather
    description: "Daily aggregated weather metrics by station."
    columns:
      - name: observation_date
        description: "Date of observations"
      - name: station_id
        description: "Station identifier"
      - name: avg_temp_degC
        description: "Average daily temperature in Celcius"
      - name: max_wind_speed_kmh
        description: "Maximum wind speed for the day"
        
  - name: extreme_weather_events
    description: "Identified extreme weather events (heat waves, cold snaps, high winds, heavy precipitation)."
    columns:
      - name: observation_date
        description: "Date of the event"
      - name: event_types
        description: "Types of extreme events detected"
      - name: station_id
        description: "Station where event was recorded"